@HOST = http://localhost:3000
@ID = 947228be-253c-48de-8961-0efd44ef7eea

###
POST {{HOST}}/api/register
Content-Type: application/json

{
  "name": "John Doe",
  "email": "mail@mail.com",
  "password": "Somerandompassword"
}

###
POST {{HOST}}/api/login
Content-Type: application/json

{
  "email": "mail@mail.com",
  "password": "Somerandompassword"
}

###
POST {{HOST}}/api/logout

###
GET {{HOST}}/api/users

###
GET {{HOST}}/api/user

###
GET {{HOST}}/api/user/{{ID}}

###
PUT {{HOST}}/api/user
Content-Type: application/json

{ "name": "John Doe", "email": "another@mail.com" }

###
DELETE {{HOST}}/api/user/

###
DELETE {{HOST}}/api/user/{{ID}}
